# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlotProduceAggregator
                                 A QGIS plugin
 Finds similar adjacent farms that can be used for the same crops.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-08-23
        copyright            : (C) 2023 by Nelson Otieno
        email                : nellchieng@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PlotProduceAggregator class from file PlotProduceAggregator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plot_produce_aggregator import PlotProduceAggregator
    return PlotProduceAggregator(iface)
