# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot_produce_aggregator_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotProduceAggregatorDialogBase(object):
    def setupUi(self, PlotProduceAggregatorDialogBase):
        PlotProduceAggregatorDialogBase.setObjectName("PlotProduceAggregatorDialogBase")
        PlotProduceAggregatorDialogBase.resize(620, 376)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlotProduceAggregatorDialogBase.sizePolicy().hasHeightForWidth())
        PlotProduceAggregatorDialogBase.setSizePolicy(sizePolicy)
        self.rasterDisplay = QtWidgets.QGraphicsView(PlotProduceAggregatorDialogBase)
        self.rasterDisplay.setGeometry(QtCore.QRect(5, 1, 491, 371))
        self.rasterDisplay.setObjectName("rasterDisplay")
        self.displaysSelectedFarms = QtWidgets.QPushButton(PlotProduceAggregatorDialogBase)
        self.displaysSelectedFarms.setGeometry(QtCore.QRect(580, 0, 31, 21))
        self.displaysSelectedFarms.setObjectName("displaysSelectedFarms")
        self.exitButton = QtWidgets.QPushButton(PlotProduceAggregatorDialogBase)
        self.exitButton.setGeometry(QtCore.QRect(580, 350, 31, 23))
        self.exitButton.setObjectName("exitButton")
        self.openRasterButton = QtWidgets.QPushButton(PlotProduceAggregatorDialogBase)
        self.openRasterButton.setGeometry(QtCore.QRect(510, 0, 51, 21))
        self.openRasterButton.setObjectName("openRasterButton")
        self.idFarmButton = QtWidgets.QPushButton(PlotProduceAggregatorDialogBase)
        self.idFarmButton.setGeometry(QtCore.QRect(510, 30, 75, 23))
        self.idFarmButton.setObjectName("idFarmButton")
        self.selectFarmButton = QtWidgets.QPushButton(PlotProduceAggregatorDialogBase)
        self.selectFarmButton.setGeometry(QtCore.QRect(510, 60, 75, 23))
        self.selectFarmButton.setObjectName("selectFarmButton")
        self.textBrowser = QtWidgets.QTextBrowser(PlotProduceAggregatorDialogBase)
        self.textBrowser.setGeometry(QtCore.QRect(510, 90, 101, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.aggregatePlotButton = QtWidgets.QPushButton(PlotProduceAggregatorDialogBase)
        self.aggregatePlotButton.setGeometry(QtCore.QRect(510, 250, 91, 23))
        self.aggregatePlotButton.setObjectName("aggregatePlotButton")
        self.generateMapButton = QtWidgets.QPushButton(PlotProduceAggregatorDialogBase)
        self.generateMapButton.setGeometry(QtCore.QRect(510, 280, 81, 23))
        self.generateMapButton.setObjectName("generateMapButton")

        self.retranslateUi(PlotProduceAggregatorDialogBase)
        QtCore.QMetaObject.connectSlotsByName(PlotProduceAggregatorDialogBase)

    def retranslateUi(self, PlotProduceAggregatorDialogBase):
        _translate = QtCore.QCoreApplication.translate
        PlotProduceAggregatorDialogBase.setWindowTitle(_translate("PlotProduceAggregatorDialogBase", "Plot-Produce Aggregator"))
        self.displaysSelectedFarms.setToolTip(_translate("PlotProduceAggregatorDialogBase", "Tutorial"))
        self.displaysSelectedFarms.setText(_translate("PlotProduceAggregatorDialogBase", "help"))
        self.exitButton.setToolTip(_translate("PlotProduceAggregatorDialogBase", "closes plugin"))
        self.exitButton.setText(_translate("PlotProduceAggregatorDialogBase", "exit"))
        self.openRasterButton.setToolTip(_translate("PlotProduceAggregatorDialogBase", "open Raster image"))
        self.openRasterButton.setText(_translate("PlotProduceAggregatorDialogBase", "Open"))
        self.idFarmButton.setToolTip(_translate("PlotProduceAggregatorDialogBase", "identify plots from Raster image"))
        self.idFarmButton.setText(_translate("PlotProduceAggregatorDialogBase", "ID Plots"))
        self.selectFarmButton.setText(_translate("PlotProduceAggregatorDialogBase", "Select Plots"))
        self.textBrowser.setToolTip(_translate("PlotProduceAggregatorDialogBase", "Selected Farms"))
        self.aggregatePlotButton.setToolTip(_translate("PlotProduceAggregatorDialogBase", "Aggregates Selected Plots"))
        self.aggregatePlotButton.setText(_translate("PlotProduceAggregatorDialogBase", "Aggregate Plots"))
        self.generateMapButton.setToolTip(_translate("PlotProduceAggregatorDialogBase", "outputs map showing aggregated plots"))
        self.generateMapButton.setText(_translate("PlotProduceAggregatorDialogBase", "Generate Map"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotProduceAggregatorDialogBase = QtWidgets.QDialog()
    ui = Ui_PlotProduceAggregatorDialogBase()
    ui.setupUi(PlotProduceAggregatorDialogBase)
    PlotProduceAggregatorDialogBase.show()
    sys.exit(app.exec_())
